### ISSUE TITLE
Unhandled exception: System.AggregateException: An error occurred while writing to logger(s). (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by felixfbecker** [dotnet/format#35] opened 2019-03-02 16:43 UTC
`dotnet-format` crashes for me in CI.

```
Unhandled exception: System.AggregateException: An error occurred while writing to logger(s). (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Tools.Logging.SimpleConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/src/Logging/SimpleConsoleLogger.cs:line 43
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.CodeFormatter.FormatWorkspaceAsync(ILogger logger, String solutionOrProjectPath, Boolean isSolution, Boolean logAllWorkspaceWarnings, Boolean saveFormattedFiles, CancellationToken cancellationToken) in /_/src/CodeFormatter.cs:line 30
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.Program.Run(String workspace, String verbosity, Boolean dryRun, IConsole console) in /_/src/Program.cs:line 68
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass3_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__16_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass3_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseDebugDirective>b__4_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__14_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__17_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseExceptionHandler>b__5_0>d.MoveNext()
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Tools.Logging.SimpleConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/src/Logging/SimpleConsoleLogger.cs:line 43
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
```

https://travis-ci.org/felixfbecker/PSKubectl/builds/500837361#L695

**Comment by CRidge** [comment] 2019-03-04 12:35
I'm seeing this too. I'm running "dotnet format" as a git hook, which fails with this. Other dotnet commands seems to work when doing it this way, but not "dotnet format".

**Comment by jmarolf** [comment] 2019-03-04 14:27
@JoeRobich 	and @jonsequitur what is the correct way log to the commandline in this case?

**Comment by jonsequitur** [comment] 2019-03-04 15:08
System.CommandLine exception handling can be customized if you want to provide a nicer message: https://github.com/dotnet/command-line-api/blob/9b70af7bcb49bce297ccfd59d653a7a5c21fe5e5/src/System.CommandLine.Tests/UseExceptionHandlerTests.cs#L111

In general, we might also consider wrapping logging calls so that they can't throw an exception that crashes the app.

**Comment by jmarolf** [comment] 2019-03-04 15:36
@jonsequitur 	My main question is how this is happening at all. It would suggest that there is no console to write output to. How do I detect this case?

**Comment by JoeRobich** [comment] 2019-03-04 15:50
I believe this is a dupe of https://github.com/dotnet/format/issues/21. There are builds on myget that include a fix.
```
dotnet install tool -g dotnet-format --version 3.0.4-prerelease.19151.2 --source https://dotnet.myget.org/F/format/api/v3/index.json
```

**Comment by jmarolf** [comment] 2019-03-12 17:06
Closing as duplicate

**Closed by jmarolf** 2019-03-12 17:06 UTC
Labels: bug, duplicate
