### ISSUE TITLE
format results in mix of tabs and spaces

### ISSUE THREAD

**Issue by jlhogan** [dotnet/format#574] opened 2020-02-25 17:19 UTC
with `.editorconfig`:
```
# http://editorconfig.org

root = true

[*]
charset = utf-8
indent_style = tab
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
insert_final_newline = false
trim_trailing_whitespace = false
```

running `dotnet format` results in files with mixed tabs and spaces. If I first format the document to use either only tabs or only spaces, I still end up with a "formatted" document that has a mix of tabs and spaces. 

I can just use the built in formatters in vscode, but want to run a format check as part of CI so `dotnet-format` seemed like the best choice. easy to set up in multiple places, easy to maintain shared config... except, it doesn't format the files consistently

**Comment by JoeRobich** [comment] 2020-02-25 18:22
@jlhogan You are right. The .editorconfig spec says that `tab_width` should inherit `indent_size` if not specified. However it seems we are keeping the default width of `4`. For a workaround you can specify `tab_width = 2` until this bug if fixed.

**Comment by sharwell** [comment] 2020-03-17 16:07
Duplicate of https://github.com/dotnet/roslyn/issues/22601

**Closed by sharwell** 2020-03-17 16:07 UTC
Labels: bug
