### ISSUE TITLE
Formatting code with an #if section

### ISSUE THREAD

**Issue by mikeage** [dotnet/format#1101] opened 2021-04-23 03:54 UTC
Hi,

Given the following code:
```cs
#if SOMETHING
good_format;
  bad_format;
#else
good_format;
  bad_format;
#endif
```

when I run dotnet-format (with no solution or anything like that, just using `dotnet-format --folder .` (my main project is a Unity project, so it doesn't really have .sln or .csproj or anything like this; this is just a minimal example), it returns the following:

```cs
#if SOMETHING
good_format;
  bad_format;
#else
good_format;
bad_format;
#endif
```
Note that the code within the `#if` is unformatted.

I realized that by default that code will not be compiled, but if I do, in fact, `#define SOMETHING`, then it will; is there an easy way I can tell dotnet-format to format everything, regardless of which particular defines might exist? Alternatively, I can probably call it multiple times with every definition (or combination of definitions of course) -- how do I tell it to add custom definitions?

**Comment by JoeRobich** [comment] 2021-05-12 21:25
@mikeage Thanks for opening this issue. Closing as it is a duplicate of https://github.com/dotnet/format/issues/783.

**Closed by JoeRobich** 2021-05-12 21:25 UTC
Labels: Resolved-Duplicate

**Comment by mikeage** [comment] 2021-05-13 02:56
oh, sorry, I don't know how I missed that when searching. Whoops

**Comment by JoeRobich** [comment] 2021-05-13 17:57
@mikeage No worries. I'd much rather mark something as duplicate than not have it reported.
