### ISSUE TITLE
Nuget package certificate appears to have expired

### ISSUE THREAD

**Issue by caseycesari** [dotnet/format#951] opened 2021-02-04 15:03 UTC
I'm seeing the following errors when trying to install the dotnet format tool:

```
dotnet tool install --global dotnet-format --version 4.0.13020

error NU3028: Package 'dotnet-format 4.0.130203' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
error NU3037: Package 'dotnet-format 4.0.130203' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
error NU3028: Package 'dotnet-format 4.0.130203' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
The tool package could not be restored.
Tool 'dotnet-format' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

This started happening on February 1st. It appears to be related to this: https://devblogs.microsoft.com/nuget/microsoft-author-signing-certificate-update/.

**Comment by JoeRobich** [comment] 2021-02-04 18:57
@caseycesari Sorry you are running into touble installing dotnet-format. I was not able to reproduce this issue locally. I've downloaded the nupkg from NuGet.org and running `nuget verify` does not report any issues.

```
dotnet nuget verify --all -v diag /Users/joeyrobichaud/Downloads/dotnet-format.4.0.130203.nupkg
```

Assuming there was an issue downloading the package, you could try clearing your nuget cache with `dotnet nuget locals --clear all` to force it to load a new copy. Or, we have a 4.1 version you could try loading (https://www.nuget.org/packages/dotnet-format/4.1.131201).

If the problem persists, could you download the nupkg, run the nuget verify command, and share the output you are given?

**Comment by caseycesari** [comment] 2021-02-05 18:23
@JoeRobich Thanks for the quick reply. Based on your feedback, and after looking into it more, it appears I'm running into this issue https://github.com/NuGet/Announcements/issues/4, which is not specific to the dotnet-format nuget package.

Thanks again.

**Comment by JoeRobich** [comment] 2021-02-05 18:35
@caseycesari Thanks for following up. Closing this issue as it is not dotnet-format specific.

**Closed by JoeRobich** 2021-02-05 18:35 UTC
Labels: Needs More Info, Question
