### ISSUE TITLE
`max_line_length` or `printwidth` support

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/format#1870] opened 2023-06-04 14:02 UTC
Hoping for a feature for configuring the `max_line_length`

> Forces hard line wrapping after the number of characters specified.

https://github.com/editorconfig/editorconfig/issues/280
https://github.com/sindresorhus/atom-editorconfig/issues/143

**Comment by sharwell** [comment] 2024-02-15 16:11
Duplicate of dotnet/roslyn#15406

**Closed by sharwell** 2024-02-15 16:11 UTC
