### ISSUE TITLE
dotnet format no longer works

### ISSUE THREAD

**Issue by damienbod** [dotnet/format#1547] opened 2022-03-11 15:39 UTC
I have be using dotnet format and think this is great. After installing .NET SDK 6.0.2 and also .NET 6.0.3 , the tool  no longer works. Wondering if this will get fixed, or if this is no longer supported?

```
>dotnet format
Unhandled exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFinderHelpers.<>c.<LoadAnalyzersAndFixers>b__0_0(Assembly assembly)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmut
```

Greetings Damien

**Comment by Romfos** [comment] 2022-03-11 22:45
I have the same problem after update

**Comment by ranma42** [comment] 2022-03-12 15:52
Is this on an ASP.Net Core project? In that case, https://github.com/dotnet/format/issues/1519 describes a similar issue.
https://github.com/dotnet/format/issues/1433#issuecomment-1055920818 proposes a workaround (using the `dotnet-format` global tool instead of the one shipped with the SDK) that you might want to try.

**Comment by damienbod** [comment] 2022-03-12 16:18
@ranma42 Thanks for the feedback, tried this and this does not solve the issue. Thanks

project: ASP.NET Core 6.0.3

**Comment by ddobbinsweb** [comment] 2022-03-24 19:15
same issue today 
```
The dotnet runtime version is '6.0.3'.
  The dotnet CLI version is '6.0.201'.
```

`dotnet format --verify-no-changes --verbosity diag ./mySolution.sln`

**Comment by JoeRobich** [comment] 2022-04-04 20:40
There is a fix coming in the next .NET 6 SDK release. In the meantime you can install `dotnet-format` as a global tool to work around this issue (See https://github.com/dotnet/format/issues/1519#issuecomment-1055922333). Closing this issue as duplicate of https://github.com/dotnet/format/issues/1519

**Closed by JoeRobich** 2022-04-04 20:40 UTC
