### ISSUE TITLE
Formatting errors to refer the violated rule in .editorconfig

### ISSUE THREAD

**Issue by Frank0101** [dotnet/format#654] opened 2020-04-25 21:07 UTC
Hi all,
would be nice to have more precise errors, possibly including what is the rule that caused them (and maybe a link to the documentation or a recognisable code).
This would help to improve the configuration or to understand how to change it in order to enable/disable some rule

**Comment by JoeRobich** [comment] 2020-08-29 18:38
Closing as a duplicate of https://github.com/dotnet/format/issues/525.

**Closed by JoeRobich** 2020-08-29 18:38 UTC
Labels: Feature Request, Resolved-Duplicate
