### ISSUE TITLE
Unable to specify project file to analyze

### ISSUE THREAD

**Issue by Pycorax** [dotnet/format#921] opened 2020-12-31 04:32 UTC
On both release version v4.0.130203 and development version v5.0.142902, it seems that attempting to use dotnet format in a folder with multiple csproj and sln files ignores the specified project file.

For example, using v5.0.142902 while Powershell is in the `D:\username\Desktop` directory, using this command:
```
dotnet format --check "D:\project-folder\project-to-analyze.csproj" -v diagnostic --fix-style warn --report "D:\project-folder\report.json"
```
Gives the intended result with proper analysis. However, using this same command in the `D:\project-folder\` directory, I get a result of:

```
Specify which project file to use because this 'D:\project-folder' contains more than one project file.
```

The same happens using v4.0.130203 with the following command (`--fix-style warn` is removed as that is not present prior to v5):
```
dotnet format --check "D:\project-folder\project-to-analyze.csproj" -v diagnostic --report "D:\project-folder\report.json"
```
I'm not sure if this is a bug or if I am using the commands wrongly.

**Comment by JoeRobich** [comment] 2021-02-05 00:24
@Pycorax Sorry you are running into issues using dotnet-format. I just want to be sure I have the scenarios correct.

This command will work as expected:
```console
D:\username\Desktop\> dotnet format --check "D:\project-folder\project-to-analyze.csproj" -v diagnostic --fix-style warn --report "D:\project-folder\report.json"
```

This command will fail:
```console
D:\project-folder\> dotnet format --check "D:\project-folder\project-to-analyze.csproj" -v diagnostic --fix-style warn --report "D:\project-folder\report.json"
```

Will the following command work?
```console
D:\project-folder\> dotnet format --check .\project-to-analyze.csproj -v diagnostic --fix-style warn --report .\report.json
```

**Comment by Pycorax** [comment] 2021-02-05 03:13
Unfortunately, the command (last one) that you provided does not work either and fails with the same result as the 2nd one.
For reference, the error message is:
`
Specify which project file to use because this 'D:\project-folder' contains more than one project file.
`

**Comment by JoeRobich** [comment] 2021-02-05 19:01
@Pycorax I was able to reproduce this behavior on Windows. Thanks for sharing the error message again. This message is coming from the dotnet CLI and not dotnet-format.

This command works for me locally. Notice that I use `dotnet-format` instead of `dotnet format`.

```console
D:\project-folder\> dotnet-format --check "D:\project-folder\project-to-analyze.csproj" -v diagnostic --fix-style warn --report "D:\project-folder\report.json"
```

@wli3 Should dotnet tools be invokable through the dotnet CLI from within folders containing multiple project files?

**Comment by Pycorax** [comment] 2021-02-05 19:03
Thanks for the fix! I can verify that it works as expected.

**Comment by JoeRobich** [comment] 2021-02-05 19:14
Closing this issue. I opened https://github.com/dotnet/sdk/issues/15697 for this issue against the CLI.

**Closed by JoeRobich** 2021-02-05 19:14 UTC
Labels: Question
