### ISSUE TITLE
Option to align attribute arguments

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/format#325] opened 2019-08-09 11:32 UTC
In tests it can be nice to align attribute arguments for a table style format:

```cs
[TestCase("text.Equals(null)",         "text", "null", true,  true)]
[TestCase("text?.Equals(null)",        "text", "null", true,  true)]
[TestCase("Equals(text, null)",        null,   null,   false, false)]
[TestCase("object.Equals(text, null)", null,   null,   false, false)]
public void IsInstanceEquals(string check, string expectedLeft, string expectedRight, bool syntaxExpected, bool symbolExpected)
{
   ...
}
```

**Comment by RikkiGibson** [comment] 2019-08-09 19:50
We have considered adding the ability to run and apply custom analyzers and code fixes when formatting. That’s the most likely way something like this would happen.

**Comment by sharwell** [comment] 2019-10-17 17:05
@JoeRobich Can you create an issue for allowing the tool to run user-specified analyzers/code fixes, and then mark this issue as a duplicate of it?

**Comment by JoeRobich** [comment] 2020-03-17 23:48
Once analyzer/fixer support is added a fixer could be written for this scenario. Analyzer tracking issue is  https://github.com/dotnet/format/issues/416

**Closed by JoeRobich** 2020-03-17 23:48 UTC
Labels: Feature Request, Resolved-Duplicate
