### ISSUE TITLE
No longer work after upgrading 5.0.301 from 6.0.101

### ISSUE THREAD

**Issue by jimmy-vo-librestream** [dotnet/format#1522] opened 2022-02-18 17:05 UTC
Here is my project structure:
```
- .config
- .husky
- src:
| - Project 1
| - Project 2
| - Project 3
| - Project 4
- package.json
```
Here is my lint-staged config in package.json
```
  "lint-staged": {
    "*.cs": [
      "dotnet format ./  --include"
    ]
  },
```

`dotnet format` was working fine with pre-commit with the sdk version 5.0.301
After I installed  6.0.101, it no longer working: 
```
Unrecognized command or argument './'

'./' was not matched. Did you mean one of the following?
...
```

The work around I have tried:
 -  specify global.json and force to use 5.0.301. This works out locally but I can't force other developers to install the same sdk version. Currently, we have to add this to gitignore, but it's inconvenient.
 -  Specify a specific project folder in `package.json` as below. But this makes committing changes 4 times slower than usual :
```
  "lint-staged": {
    "*.cs": [
      "dotnet format ./src/Project 1  --include",
      "dotnet format ./src/Project 2  --include",
      "dotnet format ./src/Project 3  --include",
      "dotnet format ./src/Project 4  --include",
    ]
  },
```

**Comment by damienbod** [comment] 2022-03-11 15:31
still broken with sdk 6.0.3

**Comment by si618** [comment] 2022-03-11 23:50
> still broken with sdk 6.0.3

Noticed the same thing, however [this workaround](https://github.com/dotnet/format/issues/1519#issuecomment-1055922333) does the job until the issue is resolved.

**Comment by JoeRobich** [comment] 2022-04-04 20:40
There is a fix coming in the next .NET 6 SDK release. In the meantime you can install `dotnet-format` as a global tool to work around this issue (See https://github.com/dotnet/format/issues/1519#issuecomment-1055922333). Closing this issue as duplicate of https://github.com/dotnet/format/issues/1519

**Closed by JoeRobich** 2022-04-04 20:40 UTC

**Comment by damienbod** [comment] 2022-04-04 20:47
@JoeRobich I tried this fix and it did not solve the issue.

Greetings Damien
